version: '3'

services: 

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod    
    container_name: app        
    networks: 
      - node-js-network
    tty: true
    volumes:
      - ./node:/usr/src/app
      - ./node/node_modules:/usr/src/app/node_modules
    ports: 
      - "3000:3000"
    depends_on: 
      - db
      
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: jazon/fullcycle:desafio-node-js-nginx-mysql_nginx
    container_name: nginx
    networks: 
      - node-js-network
    ports: 
      - "8080:80"
    depends_on: 
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    command: --innodb-use-native-aio=0
    networks:
      - node-js-network

networks: 
  node-js-network:
    driver: bridge      
