FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

# Health check
HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
    CMD curl --fail http://localhost/ || exit 1

EXPOSE 80    

CMD ["nginx", "-g", "daemon off;"]
