FROM node:15-alpine

RUN mkdir -p /usr/src/app/node_modules && chown -R node:node /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

COPY --chown=node:node . .

EXPOSE 3000

USER node

CMD ["node", "index.js"]
